name: Make TWRP Device

on:
  workflow_dispatch:
    inputs:
      IMG_URL:    
        description: 'IMG_URL'
        required: true
        default: '3.9'

jobs:
  build:
    runs-on: ubuntu-latest

  
        
    steps:
    - name: Prepare the environment
      
      run: 
        sudo apt update
        sudo apt -y install python python3 python-pip python3-pip cpio wget
       
        mkdir dt

    - name: Python3
      uses: actions/setup-python@v4
      with:
          python-version: '3.9'
          cache: 'pip'
          
    - name: Download boot or recovery img
      run: |
        aria2c "${{ github.event.inputs.IMG_URL }}"
        ls
      
    - name: Start build
      run: |
        python3 -m twrpdtgen -o dt/ *.img
    - name: ZIP device tree
      run: |
        zip -r DeviceTree.zip ./dt
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./DeviceTree.zip
        name: TWRP_Device_Tree-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: DeviceTree for twrp
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
